{% set name = "xenon" %}
{% set version = "0.8.0" %}
{% set sha256 = "cd5cad0930673d0e52609712c63fe4721a8f4c4342dc338bd7ea5fa0666b8515" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - xenon = xenon:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - radon
    - requests >=2.0
    - pyaml >=3.11
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xenon
  commands:
    - xenon -v

about:
  home: https://github.com/rubik/xenon
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Monitor code metrics for Python on your CI server

  description: |
    Xenon is a monitoring tool based on Radon. It monitors your code’s complexity.
    Ideally, Xenon is run every time you commit code. Through command line options,
    you can set various thresholds for the complexity of your code. It will fail 
    (i.e. it will exit with a non-zero exit code) when any of these requirements is
    not met.

extra:
  recipe-maintainers:
    - IgorTG
